#:schema node_modules/wrangler/config-schema.json
name = "cf-api"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[observability.logs]
enabled = true


[assets]
directory = "./assets"
binding = "ASSETS"
